// app/motivational/quote.ts

export const quotes: string[] = [
  "Your body is a temple, keep it as a polished one. ✨",
  "Consistency is the key to transformation. Don't stop! 🔥",
  "A healthy outside starts from the inside. Eat well. 🍏",
  "Your health is an investment, not an expense. 💰",
  "Motivation is what gets you started. Habit is what keeps you going. 🙌",
  "The only bad workout is the one that didn't happen. 🏃‍♀️",
  "Small progress is still progress. Keep moving. 🚀",
  "Eat for the body you want, not the body you have.",
  "Your fitness is 100% mental. Your body won't go where your mind doesn't push it.",
  "Push harder than yesterday if you want a different tomorrow. 💪",
  "Success starts with self-discipline. Stay focused.",
  "Don't wait for inspiration. Be the inspiration. ✨",
  "Sore today, strong tomorrow. Keep pushing!",
  "Action is the foundational key to all success. 🔑",
  "Your only limit is you. Break the boundaries!",
  "The hard part isn't getting your body in shape. The hard part is getting your mind in shape.",
  "Discipline is doing what needs to be done, even if you don't want to do it.",
  "Think of your workouts as important meetings you scheduled with yourself. 📅",
  "One meal doesn't make you healthy, and one cheat meal doesn't make you unhealthy. Balance is key.",
  "Fuel your body, don't just fill it. 🥗",
  "Make yourself a priority. You're worth it.",
  "Strength does not come from winning. Your struggles develop your strengths.",
  "The body achieves what the mind believes. 🧠",
  "Wake up with determination. Go to bed with satisfaction.",
  "Don't stop when you're tired. Stop when you're done. 🏁",
  "The secret of getting ahead is getting started.",
  "Your future self will thank you for the work you do today.",
  "Health is not about the weight you lose, but the life you gain. ❤️",
  "Everything you've ever wanted is on the other side of fear.",
  "Take care of your body. It's the only place you have to live. 🏠",
  "A one-hour workout is only 4% of your day. No excuses!",
  "Great things never come from comfort zones. Step out!",
  "Look in the mirror. That’s your competition. 🪞",
  "Believe in yourself and you will be unstoppable. ⚡",
  "Transformation is a process, not an event. Stay patient.",
  "Good things come to those who sweat. 💦",
  "Focus on your goal. Don't look in any direction but ahead.",
  "If you want something you've never had, you must be willing to do something you've never done.",
  "Fitness is a journey, not a destination. Enjoy the ride. 🚲",
  "Exercise is a celebration of what your body can do, not a punishment for what you ate.",
  "You don't have to be great to start, but you have to start to be great. 🌟",
  "Small daily improvements are the key to staggering long-term results.",
  "When you feel like quitting, think about why you started. 💭",
  "Sweat is just fat crying. Keep going!",
  "Be stronger than your strongest excuse. 🛡️",
  "Results take time. Don't give up because you don't see them immediately.",
  "Work hard in silence. Let your success be your noise. 📣",
  "Every journey begins with a single step. Take yours today.",
  "Your health is your greatest wealth. Protect it. 💎",
  "Stay hungry, stay healthy, and stay humble. 🙏"
];